services:
  pg:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres -p postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
